baseURL = "https://zaidaljasmi.github.io/"
languageCode = "en-us"
title = "Zaid Aljasmi"
theme = "terminal"

[params]
  # المجلد الذي يحتوي على مقالاتك
  contentTypeName = "posts"
  hideCopyright = true
  hideThemeInfo = true
  # تم تعطيل هذا لأننا أضفناه يدوياً في ملف head.html لضمان الأولوية
  # customCSS = ["terminal.css"]

  [params.logo]
    # الشعار الذي يظهر في الزاوية العلوية
    logoText = "Zaid Aljasmi"
    logoHomeLink = "/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Zaid Aljasmi's Space"

    # تم نقل السطر التالي إلى قسم params الخاص باللغة لإصلاح خطأ الإصدارات الحديثة
    [languages.en.params]
      subtitle = "Free Software Enthusiast"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "free-software"
        name = "Free Software"
        url = "/free-software"
